### PR TITLE
Inner closable overlay panel

### LINKED ISSUE #541: Closable job manager
### Describe the bug

The job manager overlay panel doesn't close when clicking the close button.

### Reproduction

_No response_

### Expected behavior

_No response_

### Platform and versions

```Shell
7.23.0
cargo 1.66.1 (ad779e08b 2023-01-10)
rustc 1.66.1 (90743e729 2023-01-10)
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by niikeec**
Able to close overplay panel from child

Closes #541

### CODE REVIEW

**Review by Brendonovich — COMMENTED** [review]
The real solution is to use a `Popover` instead of a `DropdownMenu` (idk why that wasn't done in the first place), since it has a `Close` element and handles the context for you. Would have been good to discuss this before the PR was made, but if you want to implement that now then feel free.

**Review by Brendonovich — APPROVED** [review]

**Comment by niikeec** [comment]
Can make the change if it would help

**Comment by Brendonovich** [comment]
@niikeec Feel free!

**Comment by niikeec** [comment]
@Brendonovich updated to popover

**Review by Brendonovich — APPROVED** [review]

**Pull request merged**
