### PR TITLE
remove openssl from core

### PR DESCRIPTION
**Pull request by Brendonovich**
shot in the dark but this may fix windows ci

### CODE REVIEW

**Comment by brxken128** [comment]
could windows CI be setup with the build script that @maxichrome has been working on? it might take too long to runs, or might just not work in a non-rebootable environment though (not too sure on the specifics here)

**Comment by Brendonovich** [comment]
@brxken128 That will be used eventually but atm I just want it to pass.

**Comment by brxken128** [comment]
> @brxken128 That will be used eventually but atm I just want it to pass.

that's fair 🙏

**Comment by oscartbeaumont** [comment]
The warning does seem to be gone and I have no idea why that would be given `openssl-sys` is still being override at a workspace level. Can merge this now and if the warnings come back we can review at that point.

**Review by oscartbeaumont — APPROVED** [review]

**Pull request merged**
