### PR TITLE
New Android Build Script

### PR DESCRIPTION
**Pull request by Rocky43007**
When building for Android, many errors pop up when using Rust's cargo build with Gradle Daemons. Errors ranging from building but not uploading the latest `.so` file to JNI Merging issues. Therefore, I moved the build script away from `org.mozilla.rust-android-gradle:plugin:0.9.3` into a custom `.sh` build script like the iOS `build_rust.sh` script. 

The following changes are happening to `setup.sh` due to the introduction of `cargo ndk` into the build so that we can build for the android build targets. 

I've tested it on my android location-watcher testing branch, so please let me know if any issues occur on your own machine. However, from my testing, I have found this new script to be more consistent due to it working directly from the File System instead of through Gradle.

### CODE REVIEW

**Comment by Rocky43007** [comment]
@HeavenVolkoff Hey, Utku mentioned that you were a a shell scripting wizard. I was wondering if you knew a way to get the `cargo ndk` builds to run in parallel? I tried but when killing the script, it wouldn't kill the builds running the the background, and I couldn't get the 4 outputs to show up in case one had an error for some reason.

**Comment by HeavenVolkoff** [comment]
Hey @Rocky43007 😊

I can take a look at it. Just to confirm, you want this loop to run in parallel, right? And you want the stdout and stderr of all the command to be outputted at the same time?

https://github.com/spacedriveapp/spacedrive/blob/715f47309d686b5a5d4f466853130609c57cd398/apps/mobile/modules/sd-core/android/build.sh#L44-L48

**Comment by Rocky43007** [comment]
Hey! 

Yes, because once you add more than 2 targets, the build takes almost 10 minutes (especially for x86_64 taking the longest). For the outputs, yes, just for the edge case if the code crashes for one of the builds but not the others.

**Comment by oscartbeaumont** [comment]
Correct me if I'm missing something but Cargo has a file system lock on the build directory so while you can spawn multiple "cargo build"'s they will still block each other.

I can't find any references online if the different architecture being built for means they don't block each other so I can't say for sure if they will/won't block but just checking it's been considered.

We could maybe set each of them to it's own target directory if this is a problem.

**Comment by Rocky43007** [comment]
I just checked, and you're right. We can only do one build at a time due to the file lock. This was just something I was looking to get as a nice to have. 

References: 
https://users.rust-lang.org/t/having-multi-build-together/32469
https://users.rust-lang.org/t/compile-to-mutliple-targets-at-once/21802

**Comment by Rocky43007** [comment]
One thing that needs final checking on this script is if the CI works with said script. I have no clue how to test that.

**Comment by utkubakir** [comment]
> One thing that needs final checking on this script is if the CI works with said script. I have no clue how to test that.

We can ignore Android CI. I am sure it will work fine though

**Review by utkubakir — DISMISSED** [review]
lgtm

**Comment by HeavenVolkoff** [comment]
> @HeavenVolkoff Can you take a quick look?

Taking a look rn

**Review by HeavenVolkoff — CHANGES_REQUESTED** [review]
This is just to block the PR while I fix some things

**Review by HeavenVolkoff — APPROVED** [review]
Tested on my Pixel 7 Pro, app built and launched fine, nice work @Rocky43007

**Pull request merged**
