### PR TITLE
Eslint, Updated Storage Settings and Tweaked some website features.

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
1. Incorporated eslint into the codebase in order to introduce styling rules.
2. Updated the storage settings to show the values shown on the website.
3. Tweaked some names for example Loading... to Private Library

### CODE REVIEW

**Comment by jamiepine** [comment]
can't seem to find where in this PR the grabbable space went
Screen Shot 2022-05-06 at 1 32 43 PM

**Comment by jamiepine** [comment]
Once above issues resolved will merge, great PR!

**Comment by Harry-Hopkinson** [comment]
@jamiepine I have addressed your comments.

**Comment by Harry-Hopkinson** [comment]
This PR also fixes the Typescript CI.

**Comment by jamiepine** [comment]
libraryStatistics still needs to be reverted. the hard coded values from Constants.ts shouldn't be there

**Comment by Harry-Hopkinson** [comment]
This PR should be ready now

**Comment by maxichrome** [comment]
Hey @Harry-Hopkinson — this is way too big and widely-scoped of a PR. Please create more narrowly-scoped PRs for these changes.

**Pull request closed without merging**
