### PR TITLE
Update Chinese Translations

### PR DESCRIPTION
**Pull request by Lkhsss**
# This is a translation issues

## CHANGELOG
Chinese will be used in different ways in different places. If it's just a translation program or a word-for-word translation, it's going to be very stiff. Call me if you need a translator.<a href="mailto:lkhsss1019@gmail.com">lkhsss1019@gmail.com</a>

1.[fix] `"direction": "方向",`to`"direction": "次序",`
2.[fix]`"ascending": "上升",`to`"ascending": "升序",`
3.[fix]`"item_size": "项目大小"`,to`"item_size": "图标大小",`
.........etc   太多了数不过来了。。。

## I Need Some Help
Please send me a screenshot of where these entries are in the app so I can best translate them!（Better tell me where they are in the app.）
- failed_to_open_file_with
- file_from
- file_one
- file_picker_not_supported
- for_library
- image
- incoming_spacedrop
- indexed_new_files
- indexer_rules_error
- indexer_rules_not_available
- accept_files
- app_crashed_description
- collection
- directories
- directory
- do_the_thing
- dont_have_any
- dotfile
- ends_with
- erase
- erase_a_file
- erase_a_file_description
- file_picker_not_supported
- files_many
- for_library
- gitignore
- hosted_locations
- my_sick_location

### CODE REVIEW

**Comment by Rocky43007** [comment]
Translation for:
-  `failed_to_open_file_with` is for when a user tries to open a file and fails because the system does not have a default way of opening said file. For example, macOS does not have a default application to open the contents of a `.awk` script, and this error will show up instead.
- `file_from` is for Spacedrop, and is just saying that a file is arriving with name and from a user.
- `file_one` is not used anywhere in the app currently.
- `file_picker_not_supported` is another Spacedrop translation, and is a warning for the user the file picker dialog cannot be opened on this platform.
- `for_library` is used in a feature which is not available right now, so it doesn't need to be translated at this moment.
- `image` is just a data type. Shows up here in the inspector here:
   Screenshot 2024-08-10 at 4 07 34 PM
- `incoming_spacedrop` is just a title and implies that a Spacedrop file is being received by the client. It is seen in a toast in the corner of the app.
- `indexed_new_files` is not used anywhere in the app currently.
- `indexer_rules_error` shows up when fetching the indexer rules fails for a location.
    Screenshot 2024-08-10 at 4 14 42 PM
- `indexer_rules_not_available` is the same as the error, but is the default state if there aren't any indexer rules for the location.
    Screenshot 2024-08-10 at 4 17 22 PM
- `accept_files` and `reject_files` are states for a new custom indexer rule. A full explanation can be found at the i18n tag `indexer_rule_reject_allow_label`
   Screenshot 2024-08-10 at 4 18 46 PM
- `app_crashed_description` is the default message we post when the app has reached a catastrophic issue. Example:
    Screenshot 2024-08-10 at 4 22 05 PM
- `collection` is another file type/kind. Has the same purpose as the `image` tag above.
- `directories`,`directory`, `do_the_thing` and `dont_have_any` aren't used anywhere in the app currently.
- `dotfile` is another file type/kind. Has the same purpose as the `image` tag above.
- `ends_with` is just a filter tag for search, like `contains`. Example with contains:
   Screenshot 2024-08-10 at 4 30 36 PM
- `erase`, `erase_a_file`, `erase_a_file_description` and `files_many` aren't used anywhere in the app currently.
- `gitignore` is another file type/kind. Has the same purpose as the `image` tag above.
- `hosted_locations` and `my_sick_location` aren't used anywhere in the app currently.

**Comment by Lkhsss** [comment]
> Translation for:
> 
> * `failed_to_open_file_with` is for when a user tries to open a file and fails because the system does not have a default way of opening said file. For example, macOS does not have a default application to open the contents of a `.awk` script, and this error will show up instead.
> * `file_from` is for Spacedrop, and is just saying that a file is arriving with name and from a user.
> * `file_one` is not used anywhere in the app currently.
> * `file_picker_not_supported` is another Spacedrop translation, and is a warning for the user the file picker dialog cannot be opened on this platform.
> * `for_library` is used in a feature which is not available right now, so it doesn't need to be translated at this moment.
> * `image` is just a data type. Shows up here in the inspector here:
>   Screenshot 2024-08-10 at 4 07 34 PM
> * `incoming_spacedrop` is just a title and implies that a Spacedrop file is being received by the client. It is seen in a toast in the corner of the app.
> * `indexed_new_files` is not used anywhere in the app currently.
> * `indexer_rules_error` shows up when fetching the indexer rules fails for a location.
>   Screenshot 2024-08-10 at 4 14 42 PM
> * `indexer_rules_not_available` is the same as the error, but is the default state if there aren't any indexer rules for the location.
>   Screenshot 2024-08-10 at 4 17 22 PM
> * `accept_files` and `reject_files` are states for a new custom indexer rule. A full explanation can be found at the i18n tag `indexer_rule_reject_allow_label`
>   Screenshot 2024-08-10 at 4 18 46 PM
> * `app_crashed_description` is the default message we post when the app has reached a catastrophic issue. Example:
>   Screenshot 2024-08-10 at 4 22 05 PM
> * `collection` is another file type/kind. Has the same purpose as the `image` tag above.
> * `directories`,`directory`, `do_the_thing` and `dont_have_any` aren't used anywhere in the app currently.
> * `dotfile` is another file type/kind. Has the same purpose as the `image` tag above.
> * `ends_with` is just a filter tag for search, like `contains`. Example with contains:
>   Screenshot 2024-08-10 at 4 30 36 PM
> * `erase`, `erase_a_file`, `erase_a_file_description` and `files_many` aren't used anywhere in the app currently.
> * `gitignore` is another file type/kind. Has the same purpose as the `image` tag above.
> * `hosted_locations` and `my_sick_location` aren't used anywhere in the app currently.

Thanks!

**Comment by Rocky43007** [comment]
Hey! I wanted to check in and see if you're done with all the translation changes you'd like to make.

**Comment by Lkhsss** [comment]
> Hey! I wanted to check in and see if you're done with all the translation changes you'd like to make.

That's it for now.Because there are some translations that are not used in the software.

**Review by Rocky43007 — APPROVED** [review]

**Pull request merged**
