### PR TITLE
[ENG-1828] Migrate to new Cloud Services API

### PR DESCRIPTION
**Pull request by Rocky43007**
We have been working on moving our cloud services to a new infrastructure and codebase due to many issues in development and testing for release. This PR amalgamates all core and frontend changes in the app to work with our new cloud services system and fixes problems we may have faced during development.

### CODE REVIEW

**Review by jamiepine — APPROVED** [review]

**Comment by jamiepine** [comment]
accidental approve

**Comment by HeavenVolkoff** [comment]
Weird error happening on the `CI / Type and style check`, will take a look

**Comment by HeavenVolkoff** [comment]
> Weird error happening on the `CI / Type and style check`, will take a look

Pushed fix for CI here: #2642

Some of our files were being incorrectly ignored by some `gitignore` rules, which was causing `git` to fail adding them and consequently was breaking the `autoformat` script

**Comment by jamiepine** [comment]
This PR is way too chonky 😅

**Comment by Rocky43007** [comment]
You have to embrace the chonk for the features lol

**Comment by fogodev** [comment]
Yeah, we basically ignored the chonkyness to just code as fast as possible lol, without merging untested code on main

**Pull request merged**
