### PR TITLE
Fix android thumbs

### PR DESCRIPTION
**Pull request by utkubakir**

### CODE REVIEW

**Comment by utkubakir** [comment]
Any ideas @Rocky43007 ?

**Comment by Rocky43007** [comment]
I'll take a look. I honestly don't remember the specific error the thumbnails give, so I'm running the PR right now on my phone to figure stuff out lol

**Comment by Rocky43007** [comment]
Just for documentation, putting this here. 

Found the fix. Just had to add `file://` before the `src`. Otherwise, React-Native can't find the file in the thumbnails folder.

Screenshot_2024-02-22_at_7 46 02_PM

But it works now!
Screenshot_20240222_195838_Spacedrive

**Comment by utkubakir** [comment]
Can confirm thumbs are back! Great job @Rocky43007

**Review by ameer2468 — APPROVED** [review]

**Pull request merged**
