### PR TITLE
Fix adding locations to mobile application

### LINKED ISSUE #1671: Mobile app not creating locations
### Describe the bug

When trying to add a location, it crashes with the error: `location not found <path="content://..." />`.

Just made this issue to create a PR with a working solution.

### Reproduction

1. Go to Spacedrive app
2. Click on the hamburger menu
3. Click on Add Location
4. Select a directory/folder

### Expected behavior

New location is created with no errors.

### Platform and versions

```Shell
8.9.2
cargo 1.73.0 (9c4383fb5 2023-08-26)
rustc 1.73.0 (cc66ad468 2023-10-03)
```

### Stack trace

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rocky43007**
Adds a fix to get locations working on the mobile application as right now, the application just dies when trying to add one.

However, it only works on Android right now. Depends on PR #1670 in order to see if locations break on iOS, to then fix the errors.

Closes #1671

### CODE REVIEW

**Comment by Rocky43007** [comment]
I was able to test the locations working on iOS by just copying some code from commit 784c6a8 in PR #1670. I'll wait for that PR to merge before making this PR ready for merge.

**Comment by Rocky43007** [comment]
@utkubakir Hey, the changes you pushed to main are leading to the same de serialization issue that iOS was facing before hand, but on Android now. This is after I merged main branch and did the following steps:

- `pnpm install` in `apps/mobile`
- `pnpm prep` in the root folder
- `cargo build` in `/core`

img1
img2

**Comment by utkubakir** [comment]
@Rocky43007 works on main for me? (android)

**Comment by Rocky43007** [comment]
Hm, I'll try a fresh clone of the repo then try.

**Comment by Rocky43007** [comment]
It worked, my local copy of the repo was just acting dumb I guess.

**Comment by utkubakir** [comment]
> It worked, my local copy of the repo was just acting dumb I guess.

That happens a lot with Gradle caching... Glad to see it working!

**Comment by Rocky43007** [comment]
I was facing some weird errors, so I'm rebuilding my changes from a fresh fork.

**Pull request closed without merging**
