### PR TITLE
[ENG-640, ENG-695, ENG-705, ENG-693] Categories arrow buttons + others

### PR DESCRIPTION
**Pull request by ameer2468**
**This is a collection of fixes that improves the quality/feel of the app other than adding arrow buttons to categories.**

- Better looking error message.
- Tooltip as an optional prop for 'Setting' component that is being used in settings, if the prop is passed it will render the tooltip with the info icon.
- Adjusted tooltip color
- Reset button in appearance only resets hue value instead of also theme
- Toggle for indexer rules when adding a location
- Overview arrow categories to scroll
- Masking effect for Overview category buttons, and theme options when window is smaller
- Adjusted bg color of progress bar for theme
- Minor onboarding CSS tweak for onboarding screens **(so progress dots dont touch other elements when screen is smaller)**
- Swift theme updating fixed

**Vitors commits**:

- Added support to invoke lock_app_theme function through rust.

**Nikec commits**:

- Fixed color picker dialog when creating a tag

**Screenshots**:

Screenshot 2023-06-08 at 12 29 49 PM

Screenshot 2023-06-08 at 5 01 32 PM

Screenshot 2023-06-08 at 12 31 32 PM

Screenshot 2023-06-06 at 7 02 44 PM

### CODE REVIEW

**Comment by Brendonovich** [comment]
Would like to merge #850 before this, since I did a number of changes to Categories too. If you test + review it then we can integrate this PR after.

**Comment by jamiepine** [comment]
Gorgeous!! I love it, need to fade out the X edges if possible. Use an absolutely positioned gradient mask. https://stackoverflow.com/questions/9525215/using-css-can-you-apply-a-gradient-mask-to-fade-to-the-background-over-text

**Comment by jamiepine** [comment]
https://github.com/spacedriveapp/spacedrive/assets/32987599/b92f1910-4fbf-472b-947c-65f3c906f565

I don't think this'll be the best solution for the scroll, feels way clunkier than the previous sticky method

**Comment by Brendonovich** [comment]
Fixing the sticky scroll is something I'm gonna do soon once everyone are done with their explorer work, the styles are getting out of hand and unmanageable

**Comment by ameer2468** [comment]
> I don't think this'll be the best solution for the scroll, feels way clunkier than the previous sticky method
> 
> 
> 
> https://github.com/spacedriveapp/spacedrive/assets/32987599/b92f1910-4fbf-472b-947c-65f3c906f565
> 
> 
> 
> In contrast, this is how it feels on main:
> 
> 
> 
> https://github.com/spacedriveapp/spacedrive/assets/32987599/cabc84bc-6704-47b8-b446-ea82e1b0c8b8
> 
> 
> 
> 
> 
> 

Yep tweaking this to something more reasonable.

**Review by utkubakir — APPROVED** [review]
LGTM, haven't tested the app yet, will merge when I do.

**Review by utkubakir — DISMISSED** [review]

**Review by utkubakir — CHANGES_REQUESTED** [review]
mask changes on categories (talked about it on Slack)

**Comment by Brendonovich** [comment]
4 issues in 1 PR is wayyyyy too many but looks fine

**Comment by ameer2468** [comment]
> 4 issues in 1 PR is wayyyyy too many but looks fine

Yeah next time we'll keep it smaller.

**Review by utkubakir — APPROVED** [review]

**Pull request merged**
