### PR TITLE
Rewrite of setup-system.ps1 for Windows development setup

### PR DESCRIPTION
**Pull request by voletro**
This is a full rewrite of setup-system.ps1 that sets up a user's machine for Spacedrive development. 

It currently:

1) Checks for Rust and Cargo
2) Installs pnpm (if not installed)
3) Installs the latest version of Node.js using pnpm
4) Installs LLVM (compiler for ffmpeg-rust)
4) Downloads ffmpeg and set as an environment variable

The CONTRIBUTING.md has also been updated to include info on running the script.

This PR helps close issue #77 by creating a working Windows setup script.

### CODE REVIEW

**Comment by voletro** [comment]
This commit should make that happen.

I had to add LLVM to the ci as the script downloads and runs an exe to install it.

I think the error was that I was trying to change the title and background colour of the window, so I also removed that.

**Comment by oscartbeaumont** [comment]
Thanks for making the change. It looks like CI is failing to find `libavutil`. If you have some time could you look into this. The old script was working in CI so maybe it could help as a reference for debugging.

**Comment by voletro** [comment]
Turns out GH Actions uses GITHUB_PATH and GITHUB_ENV rather than PATH and ENV. I can add a check for ci and set the correct environment variables accordingly.

**Comment by oscartbeaumont** [comment]
If you enable GitHub Actions on your fork, they will run and you can check if it is working.

**Comment by voletro** [comment]
Ok, ci now works, and ffmpeg-sys-rust now builds successfully. 

I can make a new pr if you would like, given there are so many commits in this one.

**Comment by oscartbeaumont** [comment]
I can squash the commits when we merge, so don't worry about how many it is.

It looks like CI is now failing in Linux on issue #306. I will give this one a look in the next day or so, so we can get this merged. Thanks for all your help on this PR.

**Comment by voletro** [comment]
All good, love to help.

**Review by oscartbeaumont — APPROVED** [review]

**Comment by oscartbeaumont** [comment]
Whoops, completely forgot to squash commits, my bad.

**Pull request merged**
