### PR TITLE
[ENG-1054] libheif for Linux (plus fixes) + Webp update

### PR DESCRIPTION
**Pull request by HeavenVolkoff**
- Fix building spacedrive with heif feature, should work out of the box in all supported OSes now (Linux, MacOS and Windows)
- Add custom libheif build for linux, as most distros ship a very old version that isn't compatible with `libheif-sys` crate
- Move postinstall script to a preprep script (Fix vercel and cache factory), this should be transparent for anyone developing the project
- Add custom setup for our linux shared libs in preprep script
- Implement Linux shared libs bundling for prod (now we ship libheif and pdfium on linux releases)
- Update libwep due to CVE
- Work-around appimage bundle failing to build sometimes for nor aparent reason
- Update `archive-wasm` to fix problems with recursive archives

### CODE REVIEW

**Review by Brendonovich — DISMISSED** [review]
Haven't tested on linux but am approving the `preprep` stuff

**Comment by HeavenVolkoff** [comment]
> Haven't tested on linux but am approving the `preprep` stuff

I needed to make some last minute changes due to the current code not working with git worktrees (@fogodev uses them). Should be good to go now, but maybe we wait for either @brxken128 or @fogodev to also test it on their Linux boxes and approve it too...

**Review by brxken128 — COMMENTED** [review]
Worked on my Void install flawlessly and HEIF images generated without any feature flags, will test on my Fedora 38 machine quickly too in order to cover more ground

**Review by brxken128 — APPROVED** [review]
Works great on both my Void and Fedora installs! Nice job man

**Pull request merged**
