### PR TITLE
[MOB-98] Rename, delete, & more

### PR DESCRIPTION
**Pull request by ameer2468**
**This PR does the following**:

- Several visual adjustments, making some elements smaller as they were too big.
- Browse screen location and tag sections redesigned
- Error handling for some actions **(will do a few more in another PR)**
- Rename and delete support
- Toast messages redesign

**Notes**:

There's currently issues with the Watcher which I believe Arnab is working on, some updates are not being reflected correctly.

Frame 1

### CODE REVIEW

**Comment by utkubakir** [comment]
is CI job relevant here?

**Comment by ameer2468** [comment]
> is CI job relevant here?

I just fixed the test after running it locally. Also removed a SolidJS reference + finally fixed the annoying warning message that would see on initial render in onboarding and in the app.

**Comment by utkubakir** [comment]
> > is CI job relevant here?
> 
> I just fixed the test after running it locally. Also finally fixed the annoying warning message that you would see on initial render in onboarding and in the app.

How? What was it lol

**Comment by ameer2468** [comment]
> > > is CI job relevant here?
> 
> > 
> 
> > I just fixed the test after running it locally. Also finally fixed the annoying warning message that you would see on initial render in onboarding and in the app.
> 
> 
> 
> How? What was it lol
> 
> 
> 
> I am not a fan of these multiple useEffects to be honest, those functions are supposed to only run once on the app start but that might not be the case here

That's what the warning was about. You cannot run that code unless it's in a effect. The reason is it should only be run when buildInfo data is present. It's to prevent it from running during the rendering phase.

In that case, there's no harm in using effects, as that's what it should have been in the start.

**Review by utkubakir — APPROVED** [review]

**Pull request merged**
