### PR TITLE
fix: dev tools shortcut

### PR DESCRIPTION
**Pull request by amorriscode**
The dev tools are opened using `CmdOrCrtl+Alt+I` so I updated the `CONTRIBUTING.md` to reflect this.

### CODE REVIEW

**Comment by fogodev** [comment]
https://tauri.app/v1/guides/debugging/application/#webview-console

**Comment by amorriscode** [comment]
@fogodev my bad, I was looking at the code for the menu bar that is triggered by `CmdOrCtrl+Alt+I`. Is there any reason you didn't want me to fix my mistake vs. just closing this PR?

**Comment by fogodev** [comment]
That code is MacOS specific. Sorry for just closing without much reasoning, sometimes we receive some "contributions" from bots. If you include the MacOS part alongside the already existing keybind for Linux and Windows, the PR will be good to go. I left it out because only with MacOS we have that global menu where you can just click to open dev tools, so just put the keybinds for other systems.

**Review by fogodev — CHANGES_REQUESTED** [review]
This code is MacOS specific, you can include it alongside the other keybind already there, but don't remove it please.

**Comment by amorriscode** [comment]
@fogodev totally hear you on that one! I hope to make some more meaningful commits in the future but just noticed this while getting spun up locally. I fixed the reference and also added a link to the docs you shared. 😄

**Pull request merged**
