### PR TITLE
QuickPreview Component (Needs test on MacOS)

### LINKED ISSUE #664: File previews lack a UI
### Describe the bug

Hello,

Currently, when clicking on the `open` option in a file's context menu, the app redirects you to a preview of the file. However, the current implementation is a simple `window.location.href` assignment, which results in the file preview replacing the entire app UI with no clear way to return to the previous view.

https://github.com/spacedriveapp/spacedrive/blob/8d20fcfe33bfb16f9eb1e1e12de3170661b905bb/interface/app/%24libraryId/Explorer/File/ContextMenu.tsx#L59-L64

Screenshot from 2023-03-30 01-03-27

image

### Reproduction

1. Set up and run the desktop app.
2. Add a location and open it.
3. Right-click on any file and select "Open" from the context menu.
4. The app will replace its entire UI with a preview of the file.

### Expected behavior

A simple interface for viewing file previews is displayed over the app UI

### Platform and versions

```Shell
$> pnpm --version && cargo --version && rustc --version
7.18.0
cargo 1.68.2
rustc 1.68.2 (9eb3afe9e 2023-03-27) (Arch Linux rust 1:1.68.2-1)
$> uname -a
Linux arch.shadowverse 6.2.8-200.fsync.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Mar 29 19:59:46 UTC 2023 x86_64 GNU/Linux
```

### Stack trace

```Shell
None
```

### Additional context

None

### PR DESCRIPTION
**Pull request by HeavenVolkoff**
Hello,

This PR introduces the QuickPreview component to provide a UI for file previews. The current implementation is a simple dialog that appears on top of the Explorer and displays either the file content (for images, videos, audios, and PDFs) within their appropriate native tags or the thumbnail of the selected file.

Here is a small demo:

[Screencast from 2023-03-31 20-50-28.webm](https://user-images.githubusercontent.com/9082460/229269596-86cbc688-1c62-49a8-a5de-296462d8b3dd.webm)

Currently, this implementation has only been tested on Linux. Therefore, since each Webview's native UI for media is different and Linux backend logic for serving previews is not the same as that for other OSes, I think it's important to test these changes on ~Windows~ (Already tested, see https://github.com/spacedriveapp/spacedrive/pull/665#issuecomment-1493650490) and MacOS as well. I'm in the process of setting up a dev environment on Windows, but I don't have access to a Mac. If anyone with access to one could kindly test and report any issues, it would be greatly appreciated.

In addition to the QuickPreview component, I also made the following changes to the routes that serve files:
1. Improved the handling of Range requests
2. Implemented logic to answer HEAD and OPTIONS methods
3. Handled CORS pre-flight requests
4. Expanded accepted file types
5. Improved error handling of invalid Range requests

Closes #664

### CODE REVIEW

**Comment by HeavenVolkoff** [comment]
I've refactored some of the code to improve its logic. Additionally, I've separated some of the behavior in `QuickPreview` for better readability. Although testing on both Windows and macOS is still needed to ensure consistent behavior, I think this PR is ready for a first review.

**Comment by jamiepine** [comment]
This is amazing, took something off my to-do list, thank you. Will look deeper into the code shortly.

**Comment by HeavenVolkoff** [comment]
I have successfully tested this PR on Windows and everything seems to be working as intended.

[windows.webm](https://user-images.githubusercontent.com/9082460/229412503-97b13a22-fb7d-4078-8c45-e1ae26578203.webm)

During the test, I had to revert two commits from main (b346e7a and 5782af3) because some change within them appears to have caused the file type identification to stop working. As a result, the QuickPreview component was unable to identify which tag to use, rendering it only able to display a file's thumbnail. I also observed this issue on Linux. I will gather more information regarding this and later create a new issue about it.

**Comment by fogodev** [comment]
These previews helped me to figure out some bugs regarding `file_path` creation at the `LocationWatcher`, missing the `cas_id` field. Aside from that, I also put some improvements on thumbnail generation at the watcher. 

BTW, for some reason there is a weird bottleneck when rendering some files where the height if much bigger than the width at the quick preview.

**Review by jamiepine — APPROVED** [review]

**Pull request merged**
