### PR TITLE
add: custom scrollbar

### PR DESCRIPTION
**Pull request by sr2echa**
## Changes
`.\packages\interface\src`

➖  **Removed :**
> 1. no-scrollbar
> 2. explorer-scroll

➕  **Added :**
> Universal custom scrollbar (so no need for explorer only scrollbar and a different scrollbar for overview,etc)

### Before:
image

### After:
image

#### After (scrollbar Onhover) [sorry that my cursor is not visible in the screenshot]:
image

### CODE REVIEW

**Comment by MarquesCoding** [comment]
Only issue is that it's effecting other elements within the page (buttons).

**Comment by jamiepine** [comment]
We'll need a global scrollbar, but I'd like to keep the explorer scroll completely custom, as it specifically matches the layout with compensation for the header space. 
 
CleanShot 2022-04-27 at 10 27 16@2x

**Comment by sr2echa** [comment]
@jamiepine so you want the global scrollbar to match the same style as the explorer scrollbar?
or retain the explorer scrollbar and also the global one with different styles?

**Comment by sr2echa** [comment]
@jamiepine now this is how the scrollbar looks (no hover option)
image
should I add hover effect tho?

**Comment by sr2echa** [comment]
@jamiepine like you said, now the default scrollbar (based on the overview page's scrollbar) will get applied by default if a custom scrollbar class is not mentioned. If a class is mentioned it will take attributes from the class.

lmk if i should make any other changest

**Comment by jamiepine** [comment]
the visible scrollbar on the sidebar isn't what we're looking for, thanks for the PR but had to close

**Pull request closed without merging**
