### PR TITLE
Fix all the weird eslint warnings

### PR DESCRIPTION
**Pull request by utkubakir**
^

### CODE REVIEW

**Review by ameer2468 — DISMISSED** [review]

**Comment by HeavenVolkoff** [comment]
Can I piggy-back on this PR and commit the prettier auto format changes too?

**Comment by ameer2468** [comment]
> Can I piggy-back on this PR and commit the prettier auto format changes too?

I support this, definitely a good idea.

**Comment by HeavenVolkoff** [comment]
> > Can I piggy-back on this PR and commit the prettier auto format changes too?
> 
> I support this, definitely a good idea.

Just committed, if @utkubakir thinks this should be a separate PR, I can revert it

**Comment by utkubakir** [comment]
@HeavenVolkoff oh you don't even need to ask about it, always feel free to join me :)

Thank you guys @ameer2468 @HeavenVolkoff , let's merge it. Both CI error seems faulty.

**Review by ameer2468 — APPROVED** [review]

**Pull request merged**
