### PR TITLE
Library manager

### PR DESCRIPTION
**Pull request by oscartbeaumont**
This is the PR for [ENG-132](https://linear.app/spacedriveapp/issue/ENG-132/support-for-multiple-libraries) (Support for Multiple Libraries). I would like to get this merged in before [ENG-42](https://linear.app/spacedriveapp/issue/ENG-42/p2p-communication) (P2P Communication) which will hopefully be ready later this week.

This PR is a draft as it requires UI changes so it can be merged into main without breaking the functionality of the app. The UI pages required are documented in ENG-132.

### CODE REVIEW

**Comment by jamiepine** [comment]
@oscartbeaumont could you resolve the merge conflicts? you might know how better to merge than me because I'm not fully familiar with all that is changed in this PR. Once its in sync with main I'll build the UI.

**Comment by jamiepine** [comment]
So I've finished adding basic CRUD for libraries @oscartbeaumont, only thing left is to modify the bridge to provide library context, as if you delete a library it will always re-create the database if you perform any writes, as the LibraryManager still thinks its using the deleted DB. I am doing a `libraries.retain(|l| l.id != id);` on delete, but that doesn't seem to affect it. 

Ball is in your court Oscar! :D

**Comment by oscartbeaumont** [comment]
By importing `@sd/interface` into `@sd/client` a huge amount of Typescript errors have been introduced, specially for each svg that is import into `@sd/interface`. Discussing with @Brendonovich he had the idea of removing `@sd/client` and moving it into `@sd/interface`, I think this makes sense but I want to check how you want to proceed @jamiepine.

I also think the migrations are broken as they required manual modification to work on my machine. I haven't modified them so it would be great if you could check they are working on your end. I had to remove line 32 of `migrations/20220618132721_notes/migrations.sql` and line 24 of `migrations/20220624132352_location_node_relation/migrations.sql`.

**Comment by oscartbeaumont** [comment]
I am working to fix the merge conflicts now.

**Comment by jamiepine** [comment]
I'm not going to require review on this PR, it's too large and has been worked on heavily by both myself and Oscar. I've checked that it all compiles in dev and production. It's time to move it into main.

**Comment by Brendonovich** [comment]
@jamiepine Seems like this PR was merged early. There were still bugs to be fixed.

image

With that said, this PR targets ENG-49 with its branch name but Oscar said it closes ENG-132, so it's understandable that this may not have been apparent.

**Comment by jamiepine** [comment]
"Something is wrong" isn't enough to hold up the PR when everything I've tested works. I fixed the typescript issues too, anything else can be fixed as separate fix PRs

Desperately needed this merged to avoid conflicts with PRs waiting in line, a lot of files are moved / refactored in this monolithic PR

**Comment by Brendonovich** [comment]
Just would have been good to have communication on that in Linear. Understandable that it didn't since the issue numbers didn't match up.

**Comment by oscartbeaumont** [comment]
I discussed the workaround I was doing [here](https://github.com/spacedriveapp/spacedrive/pull/258#issuecomment-1173281310). I didn't add a huge amount of detail because it's been acting differently between different runs of the app but I should have added a couple of screenshots. As stated on Slack though, the migrations being broken renders the app unusable.

The Zustand issue will also break updating notes on files.

**Comment by oscartbeaumont** [comment]
image

**Pull request merged**
