### PR TITLE
Roadmap updates

### PR DESCRIPTION
**Pull request by jamiepine**
Made a lot of improvements to the roadmap

### CODE REVIEW

**Comment by jamiepine** [comment]
Need to verify the setup script docs I added have correct commands for brew and docker, if the reviewer could ensure that would be epic!

**Comment by Rocky43007** [comment]
Homebrew command works fine. But the docker command fails:
Screenshot 2024-03-14 at 10 40 59 PM

**Comment by brxken128** [comment]
> Homebrew command works fine. But the docker command fails: Screenshot 2024-03-14 at 10 40 59 PM
> 
> Turns out, `spacedrive/spacedrive` doesn't exist on the Docker hub. Screenshot 2024-03-14 at 10 42 43 PM

I think we actually use `ghcr.io`, allow me to check quickly

**Comment by Rocky43007** [comment]
We do. Docs were updated to use `ghcr.io` instead of docker hub.

**Comment by brxken128** [comment]
> We do. Docs were updated to use `ghcr.io` instead of docker hub.

Beat me to it! I missed your commit and just saw the change as I went to edit it

**Review by brxken128 — DISMISSED** [review]

**Review by brxken128 — APPROVED** [review]
Commands, paths and grammar all look good to me!

**Pull request merged**
