### PR TITLE
[ENG-1252] Hidden files will now be 50% opacity.

### LINKED ISSUE #1514: [ENG-1252] Make hidden files slightly faded
grayish or maybe less opacity idk

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-1252](https://linear.app/spacedriveapp/issue/ENG-1252/make-hidden-files-slightly-faded)</sub>

### PR DESCRIPTION
**Pull request by Tilo-K**
Hidden files will now be grayscale and at 50% opacity. In Media-View no grayscale is applied to not mess with the image.

gridview example
listview example

Closes #1514

### CODE REVIEW

**Comment by jamiepine** [comment]
opacity is fine, grayscale looks wrong, without the blue shift it sticks out against our color scheme

**Comment by Tilo-K** [comment]
I removed the grayscale

Screenshot 2023-10-13 202541

**Comment by PineappleRind** [comment]
Finder also dims the text, what do you think

image

**Comment by Tilo-K** [comment]
Actually, I like this more yes

image

**Review by ameer2468 — APPROVED** [review]

**Comment by ameer2468** [comment]
Thank you for your contribution, looks great!

**Pull request merged**
