### PR TITLE
[ENG 946] Added zooming for image preview

### LINKED ISSUE #1165: [ENG-946] Zooming functionality for Quick Preview
<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-946](https://linear.app/spacedriveapp/issue/ENG-946/zooming-functionality-for-quick-preview)</sub>

### PR DESCRIPTION
**Pull request by Raghav-45**
Hey Spacedrive Team! 👋

I've implemented a zoomable image component. 🚀 I'm excited to enhance the user experience with this feature!

Here are some videos showcasing the implementation:

https://github.com/spacedriveapp/spacedrive/assets/77260113/43adf0f8-c39b-4ea5-b942-e97fbc3ab378

let me know your thoughts. I'm open to any feedback or suggestions for improvement. 🛠️✨

Best regards,
Aditya

Closes #1165

### CODE REVIEW

**Comment by Raghav-45** [comment]
> No scrollbar for the X axis?

it's there, but i haven't zoomed image that much in the video so that's why it's not visible

**Review by niikeec — DISMISSED** [review]
Missing translations for other languages and magnification should be reset at some point (e.g. switching between items).

**Comment by Raghav-45** [comment]
Did all these translations from my School Computer ( _My interest in open source_ )

**Comment by utkubakir** [comment]
@Raghav-45 Need help with resetting the magnification for other images? (what @niikeec mentioned)

**Comment by Raghav-45** [comment]
> @Raghav-45 Need help with resetting the magnification for other images? (what @niikeec mentioned)

Thanks for the suggestion, but I've already addressed the magnification reset. It turned out to be quite simple—I just added one line of code: `setMagnification(1);`

Screenshot 2024-04-25 120619

Now it resets zoom when we change image

**Comment by utkubakir** [comment]
Can merge this once conflicts are resolved. @Raghav-45

**Comment by Raghav-45** [comment]
@utkubakir  I Finally solved the merge conflict mountain! 🏔️, It was my first time.

**Review by utkubakir — DISMISSED** [review]

**Review by utkubakir — APPROVED** [review]

**Pull request merged**
