### PR TITLE
Add support for OS level network proxy in `pnpm prep`

### PR DESCRIPTION
**Pull request by HeavenVolkoff**
Cont. #2275

### CODE REVIEW

**Review by Rocky43007 — APPROVED** [review]
Looks good to me.

CI failure is not related to any additions from this package.

**Comment by HeavenVolkoff** [comment]
> CI failure is not related to any additions from this package.

Actually the CI failure was because of the changes, XD. I was testing this with a proxied npm registry and didn't realize that resulted in all package install urls in `pnpm-lock.yaml`  being changed to my proxied registry url, which is not accessible from GitHub

**Comment by Rocky43007** [comment]
> > CI failure is not related to any additions from this package.
> 
> Actually the CI failure was because of the changes, XD. I was testing this with a proxied npm registry and didn't realize that resulted in all package install urls in `pnpm-lock.yaml`  being changed to my proxied registry url, which is not accessible from GitHub
> 
> 

Oh, lol. I didn't see any changes where proxies are usually defined, so I completely didn't notice that the changes were in the lockfile.

**Comment by HeavenVolkoff** [comment]
Fixed it. Lockfile should be fine now

**Review by Rocky43007 — APPROVED** [review]
Actually looks good now lol

**Comment by HeavenVolkoff** [comment]
The Cypress CI error is truly unrelated to this PR, something broke upstream

**Pull request merged**
