### PR TITLE
I18n polish (zh-cn)

### PR DESCRIPTION
**Pull request by HeavySnowJakarta**
did some review on the zh-cn i18n file.

- reviewed 1st-100th lines of the file (more than 450 lines totally). It's really a thing to translate into Chinese as you have to pay attention to many aspects to let it feel not weird. Not doing traditional Chinese because I'm not proficient in it.

- also did some comments as they may be discussed

### CODE REVIEW

**Comment by utkubakir** [comment]
Conflicts are fun

**Comment by utkubakir** [comment]
@HeavySnowJakarta

**Comment by HeavySnowJakarta** [comment]
> @HeavySnowJakarta

let me have a try. i have no experience resolving conflicts and i think use github online to do it directly is slow but i'll try my best.

**Comment by HeavySnowJakarta** [comment]
I noticed since the last commit some new strings have been added and some strings have been deleted. I just accepted new strings but deleted strings were remained. I can't promise there will be no problem.

**Review by utkubakir — APPROVED** [review]
I am sure everything will be fine :D Thanks!

**Pull request merged**
