### PR TITLE
[macOS] native sidebar blur effect

### PR DESCRIPTION
**Pull request by maxichrome**
After a metric ton of trial-and-error, by way of this PR, the Spacedrive app shows macOS' native frosted-glass blur effect behind the sidebar. Took some Objective-C binding magic, but to see it working as expected is so great!

Closes ENG-81

### CODE REVIEW

**Comment by maxichrome** [comment]
Before marking as ready to review, I'd like to request @jamiepine and @benja's input on how to style the sidebar in a way that addresses the issues it has with contrast at the moment

**Comment by maxichrome** [comment]
[89df109](https://github.com/spacedriveapp/spacedrive/pull/239/commits/89df109931655a6b499174b7d8af49293fe0b32c) was probably my second-favorite commit to push during this whole thing

**Comment by maxichrome** [comment]
need to finish fixing up styles on this and it'll be mergeable :')

**Comment by benja** [comment]
This is starting to look great. However, I'm not a fan of the contrast ratio so far. Seems a bit offputting. Perhaps we can throw up some designs if this is the direction we wish to go before MVP?

**Comment by maxichrome** [comment]
any in-scope style fixes are pretty much good-to-go as far as I can see!

**Review by Brendonovich — DISMISSED** [review]
merge it it's gorgeous

**Comment by jamiepine** [comment]
Final blur results after tweaking. Approving and merging, great work!!
CleanShot 2022-06-15 at 13 52 09@2x

**Pull request merged**
