### PR TITLE
added transition to navbar background color

### PR DESCRIPTION
**Pull request by mmattbtw**
added a transition to the navbar background color, looks much better than the instant change (in my opinion).
[comparison video :^)](https://streamable.com/wrvcw4)

### CODE REVIEW

**Comment by maxichrome** [comment]
I assume this is because the PR has grown slightly old at this point, but the preview deploy failed. I'll try to manually update this tonight to resolve, but feel free to do so @mmattbtw if you have a chance before I follow up.

**Comment by mmattbtw** [comment]
interesting, works just fine on my end still. can you see what the vercel errors are?

**Review by oscartbeaumont — APPROVED** [review]

**Comment by oscartbeaumont** [comment]
Looks great

**Comment by oscartbeaumont** [comment]
I promoted this deploy to production so it should be live.

Heads up @jamiepine

**Pull request merged**
