### PR TITLE
readme: add prerequisite linux packages

### PR DESCRIPTION
**Pull request by IllusionMan1212**
Useful for first time building instead of hunting the missing packages one by one.

Taken from the ci workflow file.

### CODE REVIEW

**Comment by jamiepine** [comment]
do you need to explain how to install those packages? I'm not a linux user but the list of packages with no context is confusing still

**Comment by IllusionMan1212** [comment]
most (if not all?) debian-based distros use `apt` as the package manager so I thought it's a given. but a clarification is fine too.

**Comment by oscartbeaumont** [comment]
I was thinking of adding a script to `pnpm prep` to warn the user if they don't have everything installed but with so many Linux distros we would probs only support a few in that script.

**Comment by abhnva** [comment]
> I was thinking of adding a script to `pnpm prep` to warn the user if they don't have everything installed but with so many Linux distros we would probs only support a few in that script.

AFAIK, most of them are based on Debian, Arch and redhat.

**Comment by abhnva** [comment]
image

**Comment by oscartbeaumont** [comment]
I will review the deps in that list, I didn't have all of them installed and I have been developing fine so I am not sure we need all of them.

@abhnva what distro are you on?

**Comment by abhnva** [comment]
> I will review the deps in that list, I didn't have all of them installed and I have been developing fine so I am not sure we need all of them.
> 
> @abhnva what distro are you on?

Pop!_OS 22.04 

image

**Comment by oscartbeaumont** [comment]
@IllusionMan1212 I would be interested to know where your list of dependencies came from?

**Comment by oscartbeaumont** [comment]
@IllusionMan1212 I would be interested to know where your list of dependencies came from?

**Comment by oscartbeaumont** [comment]
If anyone comes across this and is using Fedora (`dnf`) or Arch (`pacman`) and would be willing to help me work out the dependencies for FFMPEG please ping me here or in the Discord.

**Comment by IllusionMan1212** [comment]
@oscartbeaumont I took the packages right from the [ci workflow file](https://github.com/spacedriveapp/spacedrive/blob/main/.github/workflows/ci.yml#L81-L96)

**Comment by oscartbeaumont** [comment]
I have made a [CONTRIBUTING.md](https://github.com/spacedriveapp/spacedrive/blob/contrib-guide/CONTRIBUTING.md#make-changes-locally) and [setup-system.sh](https://github.com/spacedriveapp/spacedrive/blob/contrib-guide/.github/scripts/setup-system.sh) if anyone gets stuck on this issue please give the setup script a run and ping me if you have any isssues.

**Comment by IllusionMan1212** [comment]
closing this since [CONTRIBUTING.md](https://github.com/spacedriveapp/spacedrive/blob/contrib-guide/CONTRIBUTING.md#make-changes-locally) exists now.

**Comment by yochananmarqos** [comment]
@oscartbeaumont For Arch, `ffmpeg` covers all the libs except for `libavresample` which is deprecated. The package is in the AUR if needed.

**Pull request closed without merging**
