### PR TITLE
Basic HTTP auth for sd-server

### PR DESCRIPTION
**Pull request by oscartbeaumont**
Good enough for now so I can stop bringing this up in the context of our docker image.
Screenshot 2024-04-11 at 2 08 08 PM

### CODE REVIEW

**Review by utkubakir — CHANGES_REQUESTED** [review]
Can we add little guide on docs about it? also CI's

**Comment by oscartbeaumont** [comment]
Typescript - A TS failure merged into main  (caused by another PR)
Mobile CI - Missing element (caused by another PR)
Cypress - Pushed a fix, didn't know it relied on sd-server.

**Comment by oscartbeaumont** [comment]
In terms of docs I can do but it's also autodocumenting. Auth is required in production and it will guide you through configuring it with that screenshot above.

**Review by utkubakir — APPROVED** [review]
LGTM

**Pull request merged**
