### PR TITLE
Link for codebase setup

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
Added a link for codebase setup

### CODE REVIEW

**Comment by jamiepine** [comment]
would prefer "Codebase setup" for casing

**Comment by Brendonovich** [comment]
Is this necessary? Once the contributor's guide has been written the setup process will be accessible from the "Contributing" link.

**Comment by jamiepine** [comment]
Sorry for the random close and reopen, I don't think we need this for now.

**Comment by Harry-Hopkinson** [comment]
Ok

**Pull request closed without merging**
