### PR TITLE
[ENG-954] Quick Preview for text file

### LINKED ISSUE #1173: [ENG-954] Previews for text files
Previews text files should be implemented in the near future.

<sub>From [SyncLinear.com](https://synclinear.com) | [ENG-954](https://linear.app/spacedriveapp/issue/ENG-954/previews-for-text-files)</sub>

### PR DESCRIPTION
**Pull request by Raghav-45**
Hey @utkubakir,

I made some changes in the `Thumb.tsx` and `custom_uri.rs` files. I added an iframe as shown in the first screenshot:

Screenshot (65)

However, when viewed from the inspector, it looks weird, as you can see in the second screenshot:

Screenshot (66)

I would like to know your opinion on how it should look.

Closes #1173

### CODE REVIEW

**Comment by utkubakir** [comment]
Not too bad, can we make it a bit more rounded and match the system theme? On the dark theme, background should be black

**Comment by brxken128** [comment]
> Not too bad, can we make it a bit more rounded and match the system theme? On the dark theme, background should be black

Agreed regarding the theme, although I don't see anything majorly wrong.

**Review by Raghav-45 — COMMENTED** [review]
Hey Developers @utkubakir @brxken128,

As requested, I have made it more rounded to match with the theme, and made the scroller hidden in inspector view.

Screenshot (69) g

Screenshot (70) g

But Unfortunately, iframes don't allow us to change the text color; we can only change the background color. As a result, the text will remain black on a black background, making it impossible to see the contents, even though they still will be rendered.

To achieve this functionality, i will use the Fetch API. In my opinion, the Fetch API is a more future-proof approach, especially considering the upcoming implementation of cloud features. Using Fetch would ensure better compatibility and give us more control and customizations.

I will update you after implementing all the features you have requested.

**Review by Raghav-45 — COMMENTED** [review]
Hey Developers @utkubakir @brxken128,

I'm excited to share that I've completed the requested implementations! 🚀 I've created a new `TEXTViewer` Component that renders the content of text file. The best part is, we now have complete control over it, allowing us to customize it according to our needs, and the issue of black text on a black background has been successfully resolved, as we are not using iframes anymore.

I've attached some screenshots as before:

Screenshot (94) g

Screenshot (95) g


Looking forward to your feedback and any further steps you'd like to take.

Best regards,
Aditya

**Comment by utkubakir** [comment]
@Raghav-45 This is awesome, great job! I think once the scrollbar is also dark and matches the theme, this pr will be good to go

**Review by Raghav-45 — COMMENTED** [review]
Hey @jamiepine and @utkubakir,

Thank you both for your feedback and input! I've successfully implemented the changes you requested. The scrollbar has been adjusted to match the dark theme, and I've added the horizontal padding to the text preview area as per your suggestions

Here are the screenshots illustrating the updates:
Screenshot (100) g
Screenshot (101) g

I genuinely believe that this pull request is now ready for merging. Your valuable feedback has played a crucial role in shaping these enhancements.

Best regards,
Aditya

**Comment by Raghav-45** [comment]
Hey @utkubakir and @jamiepine,

Thanks for assigning me the Issue!
I've been working on it and now I believe the Pull Request is Ready to get merged.

If there are any further adjustments or refinements you'd like me to make, please feel free to share your thoughts.

**Review by utkubakir — APPROVED** [review]
lgtm

**Pull request merged**
