### PR TITLE
[ENG-1793] Introduce error handling for sd-core-sync crate

### PR DESCRIPTION
**Pull request by fogodev**
Introducing error handling for the sd-core-sync crate, also a bunch of tweaking here and there, using stronger clippy lints.

### CODE REVIEW

**Review by HeavenVolkoff — CHANGES_REQUESTED** [review]
I am getting the following error when trying cloud sync, was this supposed to happen?
345710387-5adc4e3f-4dd1-41da-bd46-5be13dc22dc4

**Comment by ameer2468** [comment]
@fogodev @HeavenVolkoff Any updates on this? lets get it merged if there's no issues.

**Comment by fogodev** [comment]
> @fogodev @HeavenVolkoff Any updates on this? lets get it merged if there's no issues.

I would like @Rocky43007 to review if possible, as he has the most sync experience.

**Comment by Rocky43007** [comment]
I'll have it reviewed by Monday.

**Review by Rocky43007 — DISMISSED** [review]
Looks good! LGTM

**Comment by Rocky43007** [comment]
> I am getting the following error when trying cloud sync, was this supposed to happen? 345710387-5adc4e3f-4dd1-41da-bd46-5be13dc22dc4

Happens when the cloud sync ingester and sender die. Turning them off and on again works, usually.

**Comment by fogodev** [comment]
Will check them out

**Review by Rocky43007 — APPROVED** [review]

**Review by Rocky43007 — APPROVED** [review]

**Pull request merged**
