### PR TITLE
replace github star button in home cta component

### PR DESCRIPTION
**Pull request by YounesBessa**

### CODE REVIEW

**Comment by YounesBessa** [comment]
Oh okay I thought that's what Jamie wanted, he mentioned it on stream earlier today

**Comment by Brendonovich** [comment]
Ah, didn't catch that. Will leave it to him to review then

**Comment by oscartbeaumont** [comment]
Requiring an internet connection for a button to load doesn't sit right with me on an offline first desktop application.

**Comment by utkubakir** [comment]
Great PR, thank you for your contribution. Can we make the GitHub button or our waitlist button the same height?

**Comment by YounesBessa** [comment]
Yes, the width and height are adjustable, should I shrink the Github button or make the waitlist button bigger?

**Comment by utkubakir** [comment]
> Yes, the width and height are adjustable, should I shrink the Github button or make the waitlist button bigger?

Let's shrink the Github button, also instead of the middle. Can we put it to the top right and to the footer? Because we will replace the current buttons with download links soon.

**Comment by jamiepine** [comment]
Op sorry I was thinking about putting this in the footer like cal.com do.

**Comment by YounesBessa** [comment]
Okay I just reverted that first commit and put the button in the footer instead

**Comment by utkubakir** [comment]
image

The location of it is great, but it's a big boi that's for sure haha @jamiepine

**Pull request closed without merging**
