### PR TITLE
feat: shortcuts page

### PR DESCRIPTION
**Pull request by Raduc4**
This PR is just a base representation of how the shortcuts page can look like.
I'm looking for feedback to improve this.

[Issue](https://github.com/spacedriveapp/spacedrive/issues/1112)

### CODE REVIEW

**Comment by utkubakir** [comment]
Can you share screenshots?

**Comment by Raduc4** [comment]
image
image

**Comment by utkubakir** [comment]
First of all the screen needs to match our design, be more subtle and with more of our colors. I would reference some games or other applications for inspiration on the overall design though.

Here is how we display shortcuts on the context menu, I would expect similar style icons on the shortcuts page.

image

**Comment by niikeec** [comment]
Would recommend the usage of [@tanstack/react-table](https://tanstack.com/table/v8)

**Comment by utkubakir** [comment]
@Raduc4 feel free to re-open the pr if you wanna continue working on this

**Pull request closed without merging**
