### PR TITLE
Switch license to AGPL

### PR DESCRIPTION
**Pull request by Brendonovich**
Unlike GPL, the AGPL triggers when software is accessed over a network. This would stop Spacedrive and its libraries from being forked, modified and served as a SaaS platform without the modifications being made public. This does not prevent Spacedrive and its libraries from being used inside commercial projects, but it does extend the boundary of the original GPL license.

For all of Spacedrive's code to be relicensed we must get consent from all contributors. If you are a contributor, please comment on this PR indicating that you accept the license change. If you do not accept this change or fail to accept it by 27 June 8:00PM PST then your changes will be removed.

- [x] @jamiepine 
- [x] @Brendonovich  
- [x] @maxichrome 
- [x] @oscartbeaumont 
- [x] @benja 
- [x] @xPolar 
- [x] @LayZeeDK 
- [x] @KodingDev 
- [x] @sr2echa 
- [x] @CreatingBytes 
- [x] @FahimFBA 
- [x] @mmattbtw
- [x] @Harry-Hopkinson
- [x] @XSPGMike 
- [x] @he1d1 
- [x] @IllusionMan1212 
- [x] @ecwyne 
- [x] @krumware 
- [x] @stevharve 
- [x] @mark-strudwick 
- [x] @chroxify 
- [x] @TheUltDev
- [ ] @̶i̶l̶k̶k̶a̶ (Edit: Only commit fixed a broken link in the readme, not a code change. No response, not waiting.)
- [x] @CodePurble 
- [x] @abhnva 
- [x] @cnrad 
- [x] @MarquesCoding 
- [x] @alsonick 
- [x] @CodeWithBryan 
- [ ] @̶f̶i̶v̶e̶s̶t̶o̶n̶e̶s̶ (Edit: Added a single apostrophe to the readme. No response, not waiting.)
- [ ] @̶y̶k̶a̶b̶u̶s̶a̶l̶a̶h̶ (Edit: The only commit by this user was already overwritten. No response, not waiting.)
- [x] @kor-pixel 
- [ ] @̶r̶y̶a̶n̶h̶a̶t̶i̶c̶u̶s̶ (Edit: Can not be found on the contributor list. No response, not waiting.)

No external contributions should be accepted into this repository until this pull request has been merged, which will not happen until all contributors have agreed to the license change.

I accept this license change.

### CODE REVIEW

**Comment by kor-pixel** [comment]
I accept this license change.

**Comment by IllusionMan1212** [comment]
I accept this license change.

**Comment by KodingDev** [comment]
I accept this license change.

**Comment by jamiepine** [comment]
I accept this license change.

**Comment by chroxify** [comment]
I accept this license change

**Comment by mark-strudwick** [comment]
I accept this license change.

**Comment by MarquesCoding** [comment]
I accept this license change.

**Comment by CodeWithBryan** [comment]
I accept this license change.

**Comment by benja** [comment]
I accept this license change.

**Comment by krumware** [comment]
I accept this change

**Comment by CodePurble** [comment]
I accept the license change

**Comment by abhnva** [comment]
I accept this license change 👍

**Comment by XSPGMike** [comment]
I accept the licence changes.

**Comment by he1d1** [comment]
I accept the license change

**Comment by alsonick** [comment]
I accept this license change.

**Comment by LayZeeDK** [comment]
I accept this change to a restrictive license.

**Comment by xPolar** [comment]
I accept this license change.

**Comment by oscartbeaumont** [comment]
I accept the licence change.

**Comment by ecwyne** [comment]
I accept the license change

**Comment by maxichrome** [comment]
I accept this license change. 👍

**Comment by Funtimes909** [comment]
I accept the license change

**Comment by mmattbtw** [comment]
I'm not on the list, however I have made a couple of pull requests that have been merged so:

I accept this license change.

**Comment by Harry-Hopkinson** [comment]
I accept this license change

**Comment by TheUltDev** [comment]
I accept this license change.

(just seeing this now)

**Comment by maxichrome** [comment]
Update:

I've reached out to the following people outside of GitHub to try to get their consent. If we don't hear back within a few days we'll simply revert their contributions and continue ahead with the license change.

- [ ] @sr2echa (Twitter)
- [ ] @CreatingBytes (Discord)
- [ ] @FahimFBA (Email)
- [ ] @stevharve (Discord)
- [ ] @chroxify (Email)
- [ ] @ilkka (Email)
- [ ] @cnrad (Discord)
- [ ] @fivestones (Email)
- [ ] @ykabusalah (LinkedIn)

I couldn't find any contact info for @jenniferdewan so we'll be reverting their change ahead of time.

**Comment by cnrad** [comment]
I accept this license change

**Comment by FahimFBA** [comment]
I accept this license change.

**Comment by stevharve** [comment]
I accept this license change. 👍🏻

**Comment by sr2echa** [comment]
I, @sr2echa hereby accept the license change

**Comment by CreatingBytes** [comment]
I accept this license change.

**Comment by ryanhaticus** [comment]
A bit late, however I accept this license change.

**Comment by fivestones** [comment]
Hey! Also a bit late, and I may have made the very smallest contribution of anyone else here, but I too accept this license change. You can un-cross-out my name! :-) Sorry I was late.

**Comment by Sid-H** [comment]
I accept this license change.

**Pull request merged**
