### PR TITLE
[ENG-1176] Append `(x)` to the end of files instead of overwriting

### PR DESCRIPTION
**Pull request by brxken128**
During: copying, cutting, duplicating and renaming we now will append the lowest available digit to the file name if it would overwrite the source file.

The only "bug" I have ran into is when renaming say `File (2).jpg` to `File.jpg`, it will increment the name to `File (3).jpg` when it should in fact remain as `File (2).jpg` (as that's the largest available number, but it already exists so it gets incremented.

A preview:
an image showing how the new names look including the `(x)`

This may need some pretty heavy battle-testing before merge, as it could end up truncating files if it goes wrong (it shouldn't, as the action should only ever happen if the `fs::metadata` call is an `Err` (the file doesn't exist).

### CODE REVIEW

**Comment by utkubakir** [comment]
Copy/Cut/Paste/Duplicate all sounds good but I don't think it makes sense while renaming. It should error just like Finder. This also fixes the bug you encountered so win-win :)

**Review by utkubakir — CHANGES_REQUESTED** [review]
Copy/Cut/Paste/Duplicate all sounds good but I don't think it makes sense for renaming. It should error out just like Finder. This also fixes the bug you encountered so win-win :)

**Comment by brxken128** [comment]
> Copy/Cut/Paste/Duplicate all sounds good but I don't think it makes sense for renaming. It should error out just like Finder. This also fixes the bug you encountered so win-win :)

Should be resolved as of my latest few commits! :D

**Comment by fogodev** [comment]
Solved some small tech debts like unneeded clone and other nitpicks. Also found a bug with the renaming function which was having trouble with spacing like duplicating a `file (1).txt` generated a `file  (1).txt` here due. Also the solution wasn't taking into account numbers with more than 1 digit, as it would generate bad naming due to hardcoded slice with `len() - 3`

**Review by fogodev — APPROVED** [review]

**Review by fogodev — APPROVED** [review]

**Comment by brxken128** [comment]
> Solved some small tech debts like unneeded clone and other nitpicks. Also found a bug with the renaming function which was having trouble with spacing like duplicating a `file (1).txt` generated a `file (1).txt` here due to this. Also the solution wasn't taking into account numbers with more than 1 digit, as it would generate bad naming due to hardcoded slice with `len() - 3`

Oh yeah that was a very good catch, thank you!

**Review by utkubakir — APPROVED** [review]

**Pull request merged**
