### PR TITLE
Fix "open with" list ordering

### PR DESCRIPTION
**Pull request by MadisonKonig**
#1560

Closes "Open With" list order is random

Fixed the bug both on the front end, and on the back end. 

For the front, it's just a simple sorting of the values by name. 

For the back, the problem arose as it's initially put into a HashSet, which doesn't keep and order. Thankfully it is turned into a Vec before propagating as a result.  I would have liked to keep it all nested in one tidy chain of function calls, but sort doesn't return anything.
<https://users.rust-lang.org/t/chaining-functions-yields-error-method-not-found-in/93252/4>

I think @iLynxcat mentioned that it's better to do it on the backend, but the front end works just fine too since it'll be a small list. But I'll give both as solutions, and let you decide which to keep :)

### CODE REVIEW

**Comment by iLynxcat** [comment]
let's keep the JavaScript sorting now, seems that locale-sensitive compare doesn't work as we'd expect in Rust. (e.g. apps would be ordered Ferris, FeWheel, Férris [mind my terrible example], instead of Ferris, Férris, FeWheel)

**Comment by MadisonKonig** [comment]
I'm a bit confused, as the JavaScript is using `localeCompare()`, but you're wanting to keep it even though it's not meeting expectations? Did you mean to type Rust?

**Comment by iLynxcat** [comment]
> I'm a bit confused, as the JavaScript is using `localeCompare()`, but you're wanting to keep it even though it's not meeting expectations? Did you mean to type Rust?

didn't type super clearly there; proper Unicode-respecting comparison/sorting does not work as expected in Rust, and does in JS as I understand it

**Review by iLynxcat — APPROVED** [review]
Thanks for contributing this, it's been a petty annoyance for some users who'll be relieved it's fixed!

**Pull request merged**
