### PR TITLE
feat: added russian localization

### PR DESCRIPTION
**Pull request by artsiom-voitas**
Added Russian localization
Added keys in settings.json and general.tsx

### CODE REVIEW

**Comment by utkubakir** [comment]
https://github.com/spacedriveapp/spacedrive/pull/2051 can we rebase this here and the new keys?

**Review by jamiepine — APPROVED** [review]
Спасибо

**Comment by artsiom-voitas** [comment]
I've added new translation for new entries, which appeared after [More translations](https://github.com/spacedriveapp/spacedrive/pull/2051) update

**Review by utkubakir — APPROVED** [review]
выглядит неплохо

**Pull request merged**
