### PR TITLE
Translate Top Bar and new Overview to Russian and Belarusian

### PR DESCRIPTION
**Pull request by artsiom-voitas**
Translated new overview screen into Belarusian and Russian, added multiple pluralized keys for file types.

### CODE REVIEW

**Review by iLynxcat — APPROVED** [review]
Thank you so much for helping translate!

**Comment by artsiom-voitas** [comment]
> Thank you so much for helping translate!

Glad to help! 
Sorry for the inconvenience, forgot about 2 untranslated keys in top bar

**Review by iLynxcat — APPROVED** [review]

**Comment by ameer2468** [comment]
Hey @artsiom-voitas thank you for the contribution!

Please run `pnpm autoformat only-frontend` to pass formatting CI.

**Comment by iLynxcat** [comment]
The style-check CI run failed due to a bug in the CI script, fixed in #2631

**Comment by Rocky43007** [comment]
Hey, it's a different issue to why the type check is failing. For some reason, it isn't running on forks. #2631 should fix it, and we'll manually rerun the job after that PR is merged.

**Comment by iLynxcat** [comment]
good timing lol @Rocky43007, started merge on that PR now and we should be able to successfully rerun soon

**Comment by artsiom-voitas** [comment]
> The style-check CI run failed due to a bug in the CI script, fixed in #2631 

Great! Nice to hear that issue is resolved so fast!

**Comment by iLynxcat** [comment]
hey @artsiom-voitas, that PR got merged. whenever you have a second can you update your fork's changes with `main` since I don't have write access to your fork? tysm!

**Comment by artsiom-voitas** [comment]
> hey @artsiom-voitas, that PR got merged. whenever you have a second can you update your fork's changes with `main` since I don't have write access to your fork? tysm!

Hey, @iLynxcat! It is done!

**Pull request merged**
