### PR TITLE
Attempt shortcuts page

### PR DESCRIPTION
**Pull request by PineappleRind**
Relevant issue: #1112 

This is the successor of #1157

Screenshot 2023-08-24 at 10 21 41 AM

### CODE REVIEW

**Comment by utkubakir** [comment]
Need some cleanup with the paddings etc but overall, I like it!

**Comment by utkubakir** [comment]
Can we increase the padding a bit? Keys look crowded

**Comment by ameer2468** [comment]
@PineappleRind - please re-open if this is still something you're interested on working on. So far so good!

Screenshot 2023-09-14 at 1 04 39 PM

You need add some spacing in-between.

**Comment by PineappleRind** [comment]
alright, will do, thanks! 👍

**Comment by PineappleRind** [comment]
added more vertical spacing between keybinds & used `keybindForOs` for OS-specific keybinds
Screenshot 2023-09-14 at 11 51 39 AM

also @ameer2468 - I'm not sure if GitHub allows me to reopen the PR?

**Comment by ameer2468** [comment]
> added more vertical spacing between keybinds & used `keybindForOs` for OS-specific keybinds Screenshot 2023-09-14 at 11 51 39 AM
> 
> also @ameer2468 - I'm not sure if GitHub allows me to reopen the PR?

Thanks for the response. Re-opened.

I'd remove the navigation shortcuts which are: ```⌘ + ]``` and ```⌘ + [``` - these are not being used for navigation.

We also don't have shortscuts added yet for showing enclosing folder and opening a selected item.

Though space does a quick preview.

I'm gonna add support for these shortcuts soon.

**Comment by PineappleRind** [comment]
I've updated the data:

image

The `keybind` function returns a single string for macOS (like `⌘→`), so I've just been splitting it by character (`.split('')`), but realized that doesn't work for keybinds which have multiple letters in one key (like the "action with fn" action, for demonstration purposes)

Another option is to split by the plus sign:

Screenshot 2023-09-14 at 8 23 31 PM

On macOS it groups the keys together, but from what it looks like from the function, when not on macOS it will separate the keys (because the keybind function returns `key+key` instead of `keykey`)

So I could change the keybind function to return an array, or change the styling on macOS so it looks like the native context menus... I'm not really sure what to do here 😅

**Comment by ameer2468** [comment]
> I've updated the data:
> 
> image
> _(The fn action was for testing purposes, it's not there now)_
> 
> The `keybind` function returns a single string for macOS (like `⌘→`), so I've just been splitting it by character (`.split('')`), but realized that doesn't work for keybinds which have multiple letters in one key (like the "action with fn" action)
> 
> Another option is to split by the plus sign:
> 
> Screenshot 2023-09-14 at 8 35 48 PM
> On macOS it groups the keys together, but from what it looks like from the function, when not on macOS it will separate the keys (because the keybind function returns `key+key` instead of `keykey`)
> 
> So I could change the keybind function to return an array, or change the styling on macOS so it looks like the native context menus... I'm not really sure what to do here 😅

Hey thanks for the continuous effort on this!

It's completely fine to have it without the '+' - because I'm working on tooltips offering shortcuts aswell, and they will not have a '+'.

**Take this design as an example** 

image

Let's skip adding any form of '+' and just display the keys.

**Pull request closed without merging**
